on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "login to Docker hub"
        env:
          DOCKER_USER: ${{ secrets.DOCKERUSERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}

        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: "build docker image"
        run: docker build -t $DOCKER_USER/newimage .

      - name: "push image to dockerhub"
        run: docker push $DOCKER_USER/newimage
